# Generated by Django 3.2.9 on 2021-11-09 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('tkt_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(max_length=500)),
                ('ticket_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='LOW', max_length=9)),
                ('tkt_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN-PROGRESS', 'In-Progress'), ('ON-HOLD', 'On-Hold'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=12)),
                ('tkt_type', models.CharField(choices=[('INCIDENT', 'Incident'), ('REQUEST', 'Request'), ('CHANGE', 'Change'), ('PROBLEM', 'Problem')], default='INCIDENT', max_length=10)),
                ('assignment', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
